pipelines:
  default:
    - step:
        name: Run Python Script
        size: 2x
        image: python:3.10
        script:
          - echo "MADE BYE @MR_ARMAN_OWNER..."

          - pip install telebot && python3 VIP.py
